---
- name: pfsense
  box: gutobrutus/pfsense2.6.0
  hostname: pfsense
  ipaddress: 192.168.56.100
  memory: 2048
  cpus: 1

- name: srvdc
  box: gusztavvargadr/windows-server-2019-standard
  hostname: srvdc
  ipaddress: 192.168.56.120
  memory: 2048
  cpus: 1

- name: workstation-w10-01
  box: gusztavvargadr/windows-10
  hostname: master02
  ipaddress: 192.168.56.121
  memory: 2048
  cpus: 1